trigger:
  - main  # or your target branch

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: |
      git config --global user.email "paulchason@gmail.com"
      git config --global user.name "Paul Chason"
      git remote add github https://$(GITHUB_PAT)@github.com/pchason/installer-scheduling.git
      git push github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
    displayName: 'Mirror to GitHub'
